version: '3'

services:
  products:
    image: golang:1.16-alpine3.14
    depends_on:
      - db-products
    ports:
      - 8080:8080
    volumes:
      - ./docker/volumes/products/app:/go:ro
    command: ./main
    environment:
      MONGO_URL: mongodb://db-products:27017/products
      PORT: 8080
    tty: true

  products-provider-consumer:
    image: golang:1.16-alpine3.14
    depends_on:
      - db-products
    ports:
      - 50051:50051
    volumes:
      - ./docker/volumes/products-provider-consumer/app:/go:ro
    command: ./products-consumer
    environment:
      MONGO_URL: mongodb://db-products:27017/products
      PROVIDER_PORT: 50051
    tty: true

  products-provider:
    image: golang:1.16-alpine3.14
    ports:
      - 8082:8080
    environment:
      PRODUCTS_PROVIDER_CONSUMER: products-provider-consumer:50051
      PORT: 8080
    volumes:
      - ./docker/volumes/products-provider/app:/go:ro
    command: ./main
    tty: true

  merchants:
    image: golang:1.16-alpine3.14
    depends_on:
      - db-merchants
    ports:
      - 8081:8080
    volumes:
      - ./docker/volumes/merchants/app:/go:ro
    command: ./main
    environment:
      MONGO_URL: mongodb://db-merchants:27017/merchants
      PORT: 8080
    tty: true

  db-products:
    image: mongo:latest
    ports:
      - 37017:27017
    volumes:
      - ./docker/volumes/products/db:/var/lib/db

  db-merchants:
    image: mongo:latest
    ports:
      - 37018:27017
    volumes:
      - ./docker/volumes/merchants/db:/var/lib/db

  db-products-merchants:
    image: mongo:latest
    ports:
      - 37019:27017
    volumes:
      - ./docker/volumes/products-provider-consumer/db:/var/lib/db