version: '3'

services:
  products:
    image: golang:1.14.1-buster
    depends_on:
      - db-products
    ports:
      - 8080:8080
    volumes:
      - ./docker/volumes/products/app:/go:ro
    command: ./main
    environment:
      MONGO_URL: mongodb://db-products:27017/products
      PORT: 8080
    tty: true

  products-provider:
    image: golang:1.14.1-buster
    ports:
      - 8082:8080
    environment:
      PORT: 8080
    volumes:
      - ./docker/volumes/products-provider/app:/go:ro
    command: ./main
    tty: true

  merchants:
    image: golang:1.14.1-buster
    depends_on:
      - db-merchants
    ports:
      - 8081:8080
    volumes:
      - ./docker/volumes/merchants/app:/go:ro
    command: ./main
    environment:
      MONGO_URL: mongodb://db-merchants:27017/merchants
      PORT: 8080
    tty: true

  db-products:
    image: mongo:latest
    ports:
      - 37017:27017
    volumes:
      - ./docker/volumes/products/db:/var/lib/db

  db-merchants:
    image: mongo:latest
    ports:
      - 37018:27017
    volumes:
      - ./docker/volumes/merchants/db:/var/lib/db