version: '3'

services:
  products:
    image: golang:1.14.1-buster
    depends_on:
      - db-products
    ports:
      - 8080:8080
    volumes:
      - ./docker/volumes/products/app:/go:ro
    command: ./main
    env_file:
      - docker.env
    tty: true

  db-products:
    image: mongo:latest
    ports:
      - 37017:27017

    volumes:
      - ./docker/volumes/products/db:/var/lib/db