version: '3'

services:
  products:
    container_name: products
    image: golang:1.16-alpine3.14
    depends_on:
      - db-products
    ports:
      - 8080:8080
    volumes:
      - ./docker/volumes/products/app:/go:ro
    command: ./main
    environment:
      CONSUMER_PORT: 50051
      LOGO_PROVIDER: merchant-consumer:50051
      MONGO_URL: mongodb://db-products:27017/products
      PORT: 8080
    tty: true

  products-collector:
    container_name: products-collector
    image: golang:1.16-alpine3.14
    depends_on:
      - db-products
    ports:
      - 8085:8080
    volumes:
      - ./docker/volumes/products-collector/app:/go:ro
    command: ./main
    environment:
      MONGO_URL: mongodb://db-products:27017/products
      PORT: 8080
    tty: true

  products-consumer:
    container_name: products-consumer
    image: golang:1.16-alpine3.14
    depends_on:
      - db-products
    ports:
      - 50051:50051
    volumes:
      - ./docker/volumes/products-consumer/app:/go:ro
    command: ./products-consumer
    environment:
      MONGO_URL: mongodb://db-products:27017/products
      CONSUMER_PORT: 50051
    tty: true

  merchant-consumer:
    container_name: merchant-consumer
    image: golang:1.16-alpine3.14
    depends_on:
      - db-merchants
    ports:
      - 50052:50051
    volumes:
      - ./docker/volumes/merchants-consumer/app:/go:ro
    command: ./merchant-consumer
    environment:
      MONGO_URL: mongodb://db-merchants:27017/merchants
      CONSUMER_PORT: 50051
    tty: true

  merchat-catalog:
    container_name: merchat-catalog
    image: golang:1.16-alpine3.14
    ports:
      - 8082:8080
    environment:
      PRODUCTS_PROVIDER: products-consumer:50051
      PORT: 8080
    volumes:
      - ./docker/volumes/merchat-catalog/app:/go:ro
    command: ./main
    tty: true

  merchants:
    container_name: merchants
    image: golang:1.16-alpine3.14
    depends_on:
      - db-merchants
    ports:
      - 8081:8080
    volumes:
      - ./docker/volumes/merchants/app:/go:ro
    command: ./main
    environment:
      MONGO_URL: mongodb://db-merchants:27017/merchants
      PORT: 8080
    tty: true

  ftp-client:
    container_name: ftp-client
    image: golang:1.16-alpine3.14
    depends_on:
      - ftp
    ports:
      - 8084:8080
    volumes:
      - ./docker/volumes/ftp-client/app:/go:ro
    command: ./main
    environment:
      FTP: "ftp:21"
      FTP_USERNAME: username
      FTP_PASSWORD: password
      PRODUCT_PATH: "/products"
      PORT: 8080
    tty: true

  db-products:
    container_name: db-products
    image: mongo:latest
    ports:
      - 37017:27017
    volumes:
      - ./docker/volumes/products/db:/var/lib/db

  db-merchants:
    container_name: db-merchants
    image: mongo:latest
    ports:
      - 37018:27017
    volumes:
      - ./docker/volumes/merchants/db:/var/lib/db

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/volumes/frontend/build:/usr/share/nginx/html
    ports:
      - 80:8080
      - 9090:9090
      - 8083:8081
    restart: always

  ftp:
    container_name: ftp
    image: fauria/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./docker/volumes/ftp/products:/home/vsftpd/username/products
    environment:
      FTP_USER: username
      FTP_PASS: password
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
    restart: always